phrases = [
         "“Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.”\n- Henry Wadsworth Longfellow","“I didn't want to wake up. I was having a much better time asleep. And that's really sad. It was almost like a reverse nightmare, like when you wake up from a nightmare you're so relieved. I woke up into a nightmare.”\n- Ned Vizzini",
         "“There are wounds that never show on the body that are deeper and more hurtful than anything that bleeds.”\n- Laurell K. Hamilton, Mistral's Kiss",
         "“I can't eat and I can't sleep. I'm not doing well in terms of being a functional human, you know?”\n- Ned Vizzini",
         "“I'm not afraid of death; I just don't want to be there when it happens.”\n- Woody Allen", 
         "“Have no fear of perfection - you'll never reach it.”\n- Salvador Dali",
         "I was lord of this place, before the crows and rats made it their domain.",
         "Driving out corruption is an endless battle, but one that must be fought.",
         "Room by room, hall by hall, we reclaim what is ours.",
         "A spark without kindling is a goal without hope.",
         "A moment of respite, a chance to steel one-self against the coming horrors.",
         "A moment of valour shines brightest against the backdrop of despair.",
         "Beacons in the darkness, stars in the emptiness of the void.",
         "You will endure this lost and learn from it.",
         "Failure tests the metal of heart, brain, and body.",
         "A setback, but not the end of things!",
         "And now the true test. Hold fast! Or expire.",
         "More dust… more ashes… more disappointment.",
         "Death waits… for the slightest lapse in concentration.",
         "Even the aged oak will fall to the tempest’s winds.",
         "Some may fall… but their knowledge lives on.",
         "Alone in the woods or tunnels, survival is the same. Prepare, persist, and overcome.",
         "What goes up must come down. Ask any system administrator.",
         "Write a wise saying and your name will live forever.\n - Anonymous, ironically",
         "He who dies with the most toys is, nonetheless, still dead.",
         "Why are people racist? We all taste the same",
         "I may be ugly, but my music taste is better than yours",
         ]

horror = [
        "I begin tucking him into bed and he tells me, “Daddy check for **monsters** under my bed.” I look underneath for his amusement and see him, **another him**, under the bed, staring back at me quivering and whispering, “Daddy, **there’s somebody on my bed.**”", 
        "The doctors told the **amputee** he might experience a phantom limb from time to time. Nobody prepared him for the moments though, when he felt **cold fingers** brush across his phantom hand.", 
        "I can’t **move, breathe, speak or hear** and it’s so **dark** all the time. If I knew it would be this lonely, I would have been **cremated** instead.", 
        "Don’t be scared of the **monsters**, just look for them. Look to your left, to your right, under your bed, behind your dresser, in your closet but never look up, **she hates being seen.**", 
        "I woke up to hear **knocking on glass**. At first, I though it was the window until I heard it come from the **mirror again.**", 
        "They celebrated the first successful **cryogenic freezing**. He had no way of letting them know he was **still conscious.**", 
        "She wondered why she was casting **two shadows**. Afterall, there was only a **single lightbulb.**", 
        "**It** sat on my shelf, with thoughtless **porcelain eyes** and the prettiest pink doll dress I could find. Why did she have to be **born still?**", 
        "The grinning **face** stared at me from the **darkness** beyond my bedroom window. I live on the **14th floor.**", 
        "Working the night shift **alone** tonight. There is a **face** in the cellar staring at the security camera.", 
        "They delivered the **mannequins** in bubble wrap. From the main room I begin to hear **popping.**", 
        "You wake up. She **doesn’t.**", 
        "You get home, tired after a long day of work and ready for a relaxing night alone. You reach for the light switch, but another **hand** is **already there.**", 
        "My daughter won’t stop **crying** and **screaming** in the **middle of the night**. I visit her **grave** and ask her to stop, but it doesn’t help.", 
        "Day 312. Internet still **not working.**", 
        "I needed to quickly run a **SQL command** to update a **single row** in an Oracle DB table at work. To my horror, it came back with **“–2,378,231 rows affected.”**", 
        "You’re laying in bed and with your **feet dangling out of the covers**. You feel a **hand** grab your **feet**.",
        "The funeral attendees never came out of the **catacombs**. Something locked the **crypt door from the inside.**",
        "My **wife** woke me up last night to tell me there was an **intruder in our house**. She was **murdered** by an intruder 2 years ago.",
        "The officer finally got back to me. The call was coming from **inside the house.**",
        "I was having a pleasant dream when what sounded like **hammering** woke me. After that, I could barely hear the muffled sound of **dirt** covering the **coffin** over my own **screams.**",
        "The **last man on Earth** sat alone in a room. There was a **knock** at the door.",
        "You hear the **scream** across the hallway, but your eyes **won’t open and you can’t move.**",
        "I looked out my window. The stars had **gone away.**",
        "> I can’t sleep\nshe whispered, crawling into bed with me. I woke up cold, clutching the dress she was **buried in.**",
        "I just saw my reflection **blink**.",
        "I kiss my **wife and daughter** goodnight before I go to sleep. When I wake up, I’m in a padded room and the nurses tell me it was **just a dream.**",
        "I peeked outside. The pizza delivery guy is at the door, but I didn’t **order a pizza** - and definitely not from someone wearing a **pig mask.**",
        "If you get scared at night, don’t keep your eyes **closed** for too long. There’s a reason you’re scared, and now you can’t see **it** approach.",
        "I used a **Ouija board** yesterday, but I only asked one question and put it away. I got my answer today - **written in blood on my ceiling**.",
        "The **wailing** from the baby monitor just won’t stop. Problem is, my daughter is with her mother this weekend… over **200 miles away.**",
        "My husband woke me up by kissing my cheek when he got home late. This morning I checked my phone - he **stayed with a friend last night.**",
        "I’ve been looking for **my sister** all day long. But I don’t remember where I put all of **the pieces.**",
        ]

tech_jokes = [
        "There are 10 types of people in the world: those who understand binary, and those who don't.",
        "How many programmers does it take to change a light bulb?\n> ||None. It's a hardware problem.||",
        "A SEO couple had twins. For the first time they were happy with duplicate content.",
        "Why is it that programmers always confuse Halloween with Christmas?\n- Because 31 OCT = 25 DEC",
        "Why do they call it hyper text?\n> ||Too much JAVA.||",
        "In order to understand recursion you must first understand recursion.",
        "Why do Java developers wear glasses?\n> ||Because they can't C#||",
        'Two bytes meet. The first byte asks,\n> Are you ill?\nThe second byte replies, \n> No, just feeling a bit off.',
        "If you put a million monkeys on a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl programs.",
        "There's a band called 1023MB. They haven't had any gigs yet. ",
        "There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors.",
        "Whoever said that the definition of insanity is doing the same thing over and over again and expecting different results has obviously never had to reboot a computer.",
        "Autocorrect can go straight to he’ll.",
        "Did you hear about the monkeys who shared an Amazon account?\n> They were Prime mates.",
        "Some things Man was never meant to know. For everything else, there’s Google. ",
        "In order to understand recursion, you must first understand recursion.",
        "An SQL Query walks into a bar and sees two tables. He walks up and asks,\n> Can I join you? ",
        "The truth is out there. Anybody got the URL?! ",
        "Computers are like air conditioners: they stop working when you open Windows. ",
        "Internet Explorer 11 will allow you to download Google Chrome up to 5 times faster ",
        "Internet Explorer: The best browser for downloading another browser.",
        "If at first you don’t succeed; call it version 1.0. ",
        "I’m not anti-social; I’m just not user friendly. ",
        "Programmers are tools for converting caffeine into code.",
        "My attitude isn’t bad. It’s in beta. ", 
        "The box said ‘Requires Windows 7 or better’. So I installed LINUX...",
        "Why are iPhone chargers not called Apple Juice?!",
        "I just got fired from my job at the keyboard factory. They told me I wasn't putting in enough shifts.",
        "We'll we'll we'll...if it isn't autocorrect.",
        "I saw a driver texting and driving. It made me so mad I threw my beer at him.",
        "Thanks to autocorrect, 1 in 5 children will be getting a visit from Satan this Christmas.",
        "Autocorrect has become my worst enema.",
        "The guy who invented predictive text died last night. His funfair is next monkey.",
        "The guy who invented auto-correct for smart phones passed away today. Restaurant in peace.", 
        ]

jokes = [
        "Don't interrupt someone working intently on a puzzle. Chances are, you'll hear some crosswords.",
        "I'm a big fan of whiteboards. I find them quite re-markable.",
        "Yesterday, a clown held the door open for me. It was such a nice jester!",
        "The machine at the coin factory just suddenly stopped working, with no explanation. It doesn't make any cents!",
        "I was going to make myself a belt made out of watches, but then I realized it would be a waist of time.",
        "Did you hear about the auto body shop that just opened? It comes highly wreck-a-mended.",
        "All these sea monster jokes are just Kraken me up.",
        'Shout out to the people who ask what the opposite of "in" is.',
        "I'm only friends with 25 letters of the alphabet. I don't know Y.",
        "Want to hear something terrible? Paper. See? I told you it was tear-able.",
        "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
        "Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea. ",
        "The past, the present, and the future walk into a bar… It was tense.",
        "Atoms are untrustworthy little critters. They make up everything!",
        "6:30 is the best time on a clock… hands down.",
        "Did you hear about the man who was accidentally buried alive? It was a grave mistake.",
        "I had to clean out my spice rack and found everything was too old and had to be thrown out. What a waste of thyme.",
        "I hate how funerals are always at 9 a.m. I’m not really a mourning person.",
        "I lost my job at the bank on my very first day. A woman asked me to check her balance, so I pushed her over.",
        "Ray’s friends claim he’s a baseball nut. He says they’re way off base.",
        "Why not go out on a limb? Isn't that where all the fruit is?",
        "My ex used to hit me with stringed instruments. If only I had known about her history of violins.",
        "Did you hear about the 2 silk worms in a race? It ended in a tie!",
        "Having sex in an elevator is wrong on so many levels.",
        "Someone stole my toilet and the police have nothing to go on.",
        "Last time I got caught stealing a calendar I got 12 months.",
        "What do you call a laughing motorcycle? A Yamahahaha.",
        "A friend of mine tried to annoy me with bird puns, but I soon realized that toucan play at that game.",
        "I wasn't originally going to get a brain transplant, but then I changed my mind.",
        "I can't believe I got fired from the calendar factory. All I did was take a day off.",
        "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
        "My three favorite things are eating my family and not using commas.",
        "How do you make a pirate furious? Take away the p.",
        "Been reading up on the thesaurus lately because a mind is a terrible thing to garbage.",
        "How many blondes does it take to screw in a lightbulb? Need to know ASAP.",
        "What do you mean, I didn’t win? I ate more wet T-shirts than anyone else.",
        "Parallel lines have so much in common. It’s a shame they’ll never meet.",
        "I don't get the point of decimals. I'm more partial to fractions.",
        "Old mathematicians never die. They just disintegrate",
        "When algebra teachers retire, how do they cope with the aftermath?",
        "I knew a mathematician who couldn't afford lunch. He could binomial.",
        "Which composer likes tea the most? Chai-kovsky.",
        "How did the turkey win the talent show? With his drum-sticks.",
        "What do you get when you drop a piano down a mineshaft?\n> ||A-flat minor.||",
        "What’s an avocado’s favorite music?\n> ||Guac ‘n’ roll.||",
        "What do you call a musician with problems?\n> ||A trebled man.||",
        "What do you call a cow that can play a musical instrument?\n> ||A moo-sician.||",
        "What was Beethoven’s favorite fruit?\n> ||BA-NA-NA-NAAAAAA.||",
        "Someday I will learn to stop procrastinating, but today is not that day.",
        "What time did the man go to the dentist?\n> ||Tooth hurt-y.||",
        "Did you hear about the guy who invented Lifesavers?\n> ||They say he made a mint.||",
        "A ham sandwich walks into a bar and orders a beer. Bartender says,\n> Sorry we don't serve food here.",
        "Whenever the cashier at the grocery store asks my dad if he would like the milk in a bag he replies,\n> No, just leave it in the carton!",
        "Why do chicken coops only have two doors? Because if they had four, they would be chicken sedans!",
        "Me:\n> Dad, make me a sandwich!\n Dad:\n> Poof, You’re a sandwich!",
        "Why did the Clydesdale give the pony a glass of water?\n> ||Because he was a little horse!||",
        "Me:\n> Hey, I was thinking… My dad:\n> I thought I smelled something burning.",
        "How do you make a Kleenex dance?\n> ||Put a little boogie in it!||",
        "Whenever we drive past a graveyard my dad says,\n> Do you know why I can’t be buried there?\n And we all say,\n> Why not?\n And he says,\n> Because I’m not dead yet!",
        "Two peanuts were walking down the street. One was a salted.",
        "How do you make holy water? You boil the hell out of it.",
        "When I went to choir practice — Dad:\n> Don’t forget a bucket.\nMe:\n> Why?\nDad:\n> To carry your tune.",
        "Two guys walk into a bar, the third one ducks.",
        "We were getting fast food when the lady at the window said,\n> Any condiments?\nMy dad responded,\n> Compliments? You look very nice today!",
        "A woman is on trial for beating her husband to death with his guitar collection. Judge says,\n> First offender?\n She says, No, first a Gibson! Then a Fender!",
        "Anytime I do something smart my dad says,\n> 'Wow, you're a fart smella...I mean smart fella!'",
        "I had a dream that I was a muffler last night. I woke up exhausted!",
        "There’s a fine line between a numerator and a denominator. (…Only a fraction of people will get this joke.)",
        "Did you hear about the first restaurant to open on the moon?\n> ||It had great food, but no atmosphere.||",
        "What do dentists call their x-rays?\n> ||Tooth pics!||",
        "I bought some shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
        "I told my girlfriend she drew her eyebrows too high. She seemed surprised.",
        "My dog used to chase people on a bike a lot. It got so bad, finally I had to take his bike away.",
        "I'm so good at sleeping. I can do it with my eyes closed.",
        "My boss told me to have a good day.. so I went home.",
        "Why is Peter Pan always flying?\n> ||He neverlands.||",
        "A woman walks into a library and asked if they had any books about paranoia. The librarian says:\n> They're right behind you!",
        "The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
        "Why do blind people hate skydiving?\n> ||It scares the hell out of their dogs.||",
        "When you look really closely, all mirrors look like eyeballs.",
        "What do you call a guy with a rubber toe?\n> ||Roberto.||",
        "What did the pirate say when he turned 80 years old?\n> ||Aye matey.||",
        "My wife told me I had to stop acting like a flamingo. So I had to put my foot down.",
        "I couldn't figure out why the baseball kept getting larger. Then it hit me.",
        "Why did the old man fall in the well?\n> ||Because he couldn't see that well.||",
        "I ate a clock yesterday, it was very time consuming.",
        "Whatdya call a frenchman wearing sandals?\n> ||Phillipe Phillope.||",
        "A blind man walks into a bar. And a table. And a chair.",
        "I know a lot of jokes about unemployed people but none of them work.",
        "What's orange and sounds like a parrot?\n> ||A carrot.||",
        "Did you hear about the italian chef that died?\n> ||He pasta way.||",
        "Why couldn't the bicycle stand up?\n> ||Because it was two tired!||",
        "My wife accused me of being immature. I told her to get out of my fort.",
        "Where do you find a cow with no legs?\n> ||Right where you left it.||",
        "When a deaf person sees someone yawn do they think it’s a scream?",
        "As I suspected, someone has been adding soil to my garden. The plot thickens.",
        "How do crazy people go through the forest? They take the physco path.",
        "And the lord said unto John,\n> Come forth and you will receive eternal life.\n John came fifth and won a toaster.",
        "What did the traffic light say to the car?\n> ||Don’t look! I’m about to change||",
        "I just wrote a book on reverse psychology. Do **not** read it!",
        "What did one hat say to the other?\n> ||You stay here. I’ll go on ahead.||",
        "Why wouldn’t the shrimp share his treasure?\n> ||Because he was a little shellfish.||",
        "What did the left eye say to the right eye?\n Between you and me, something smells.",
        "What did the father tomato say to the baby tomato whilst on a family walk?\n> ||Ketchup.||",
        "Why is there a fence around a cemetery?\n> ||People are dying to get in.||",
        "Did you hear about the kidnapping in the park?\n> ||They woke him up.||",
        "How does Darth Vader like his toast?\n> ||On the dark side.||",
        "When will the little snake arrive?\n> ||I don't know but he won't be long...||",
        "Why do fish live in salt water?\n> ||Because pepper makes them sneeze!||",
        "What has three letters and starts with gas. A Car.",
        "How do you get an astronaut's baby to sleep?\n> ||You rocket!||",
        "I think i would like a job cleaning mirrors, it's just something I could really see myself doing.",
        "Why did it take so long for the pirates to learn the Alphabet?\n> ||They got stuck at C.||",
        "I took the shell off my racing snail thinking it would make him go faster, if anything it made him more sluggish.",
        "Somebody stole my microsoft office and they're going to pay - you have my Word.",
        "Just remember - you never really completely useless, you can always serve as a bad example.",
        ]

### TODO Discord formatting
stories = [
        "A father is laying in bed after just waking up, he grabs the baby monitor and walks to his desk in his office at home, he has his baby on the baby monitor and hears his wife singing to her, he cracks a smile as he hears his wife\n> Go to sleep… go to sleep…\nWhen suddenly the front door opens up and his wife comes in with groceries.",
        "A young boy is sleeping in his bed on a usual night. He hears footsteps outside his door, and peeks out of his eyes to see what is happening. His door swings open quietly to reveal a **murderer** carrying the corpses of his **parents**. After silently propping them up on a chair, he writes something on the wall in the blood of the dead bodies. He then hides under the **child's bed.**",
        "Mommy told me never to go in the basement, but I wanted to see what was making that noise. It kind of sounded like a puppy, and I wanted to see the puppy, so I opened the basement door and tiptoed down a bit. I didn’t see a puppy, and then Mommy yanked me out of the basement and yelled at me. Mommy had never yelled at me before, and it made me sad and I cried. Then Mommy told me never to go into the basement again, and she gave me a cookie. That made me feel better, so I didn’t ask her why **the boy in the basement** was making noises like a puppy, or why he had **no hands or feet.**",
        "A man leaves his house every morning to walk to work and passes a mental hospital surrounded by a wooden fence. Every morning the patients are out in the yard and he can hear them saying in unison,\n> 10, 10, 10, 10, 10.\nOne day, he gets curious and looks through a hole in the fence. Suddenly, a stick shoots out and pokes him in the eye.\n> FUCK!\nHe says to himself while walking away pissed off he can hear the patients saying,\n> “11, 11, 11, 11, 11”",
        "I check into small hotel a few kilometers from Kiev. It is late. I am tired. I tell woman at desk I want a room. She tells me room number and give key. “But one more thing comrade; there is one room without number and always lock. Don’t even peek in there.” I take key and go to room to sleep. Night comes and I hear trickling of water. It comes from the room across. I cannot sleep so I open door. It is coming from room with no number. I pound on door. No response. I look in keyhole. I see nothing except red. Water still trickling. I go down to front desk to complain. “By the way who is in that room?” She look at me and begin to tell story. There was woman in there. Murdered by her husband. Skin all white, except her eyes, which were red.",
        "A woman survivalist and trained outdoors guide who loves to go solo camping. Returns home after 2 weeks of being in the bush and not seeing a single soul. Develops her disposable camera film to find a roll of film with numerous pictures of **her sleeping at night**, on **different** nights. She has never gone camping or hiking since.",
        "There was a story about how a guy was driving through the mountains (ex army) and came across a crash. The car wasn’t damaged at all and almost deliberately placed in the middle of the road. He drove past and saw 2 people lying in the road. He pulls up in front of the “crash” and then looks back to see the people sat up and 20 or so eyes reflecting in his taillights from the surrounding bushes. He slams on the gas and goes. This story scares me because this kind of thing does happen with “mountain tribes” who are either **cannibalistic or crazy.**",
        "The last thing I saw was my alarm clock flashing **12:07** before she pushed her long rotting nails **through my chest**, her other hand muffling my **screams**. I sat bolt upright, relieved it was only a dream, but as I saw my alarm clock read **12:06**, I heard my closet door creak open.",
        "For years, we heard the little voices and footsteps of the ghost children in our old farmhouse, and we got used to them. Then one day they went quiet, which should have been our own cue to leave.",
        "I slowed down for the car accident and saw the vehicle was identical to the one I was driving, and the body EMTs were pulling out of the car was wearing a dress identical to one I had hanging in my closet - a dress I had bought on vacation several states away years before and had never seen in any local stores.",
        ]

### Gifs
gifs_hmm = [
        "https://giphy.com/gifs/reaction-confused-will-smith-y3QOvy7xxMwKI",
        "https://giphy.com/gifs/reaction-confused-will-smith-y3QOvy7xxMwKI",
        "https://giphy.com/gifs/nba-celebrity-kPtv3UIPrv36cjxqLs",
        "https://giphy.com/gifs/hulu-star-trek-the-original-series-l0MYNLZmHQbryIMFO",
        "https://giphy.com/gifs/archiecomics-archie-comics-archies-weird-mysteries-something-is-haunting-xT1XH40gX007yEViqQ",
        "https://giphy.com/gifs/veephbo-hbo-veep-julia-louis-dreyfus-l46CdKpJzMLglrS3S",
        ]
gifs_what = [
        "https://giphy.com/gifs/everyone-brown-shaun-LyJ6KPlrFdKnK",
        "https://giphy.com/gifs/reaction-2wSaulb0fsDydh0IoB",
        "https://giphy.com/gifs/josh-hutcherson-craig-robinson-gunpowder-sky-xT9IgKK9NVmEZxYTeM",
        "https://giphy.com/gifs/nbcsvu-svu-law-and-order-special-victims-unit-wKd9dVdx0A75gBa9CI",
        "https://giphy.com/gifs/hulu-pen15-hulu-originals-show-xWCeUvh0ECyMvOU6m2",
        ]
gifs_ok = [
        "https://giphy.com/gifs/thumbs-up-deadwood-no-problem-CvZuv5m5cKl8c",
        "https://giphy.com/gifs/shaun-the-sheep-movie-not-my-gif-2016-oscar-nominations-tIeCLkB8geYtW",
        "https://giphy.com/gifs/leroypatterson-3oz8xQQP4ahKiyuxHy",
        "https://giphy.com/gifs/1ZkMDj88mQ1rO",
        "https://giphy.com/gifs/Originals-thumbs-up-congrats-you-did-it-3o6Zt8qDiPE2d3kayI",
        ]
gifs_anyways = [
        "https://giphy.com/gifs/doctor-who-david-tennant-confused-G1fQl836pXEUo",
        "https://giphy.com/gifs/anyway-anyways-anyhoo-U44Zg96RLzlHIQavOf",
        "https://giphy.com/gifs/jerseyshore-jersey-shore-family-vacation-223-LOu8FUhPgpeUAi0wiu",
        "https://giphy.com/gifs/jerseyshore-season-3-premiere-part-1-W1TTs7a4A7TaSrFGl8",
        "https://giphy.com/gifs/true-and-the-rainbow-kingdom-funny-netflix-1oEU9aVVGAvo25E7X9",
        ]
gifs_hello = [
        "https://giphy.com/gifs/the-simpsons-hello-hi-ASd0Ukj0y3qMM",
        "https://giphy.com/gifs/reaction-mood-mXig3LqjFyyvKvHtD2",
        "https://giphy.com/gifs/waitressmusical-musical-broadway-2yrZdvFsS9W4qhzDhM",
        "https://giphy.com/gifs/sailor-mars-yyVph7ANKftIs",
        "https://giphy.com/gifs/cant-hardly-wait-kW8mnYSNkUYKc",
        ]
gifs_uhh = [
        "https://giphy.com/gifs/real-housewives-rhoa-brandi-glanville-WSO1ZT9sug15C",
        "https://giphy.com/gifs/memecandy-lmurRRhV169gDW7iN4",
        "https://giphy.com/gifs/cbc-listening-emma-hunter-fwasmr-RKRqLrDILZJCF1PhjM",
        "https://giphy.com/gifs/CulturaJubile-cultura-medium-9xijGdDIMovchalhxN",
        "https://giphy.com/gifs/fallontonight-jimmy-fallon-mood-tonight-show-BMtGb8JSk2Ln1cnPMA",
        ]
gifs_yes = [
        "https://giphy.com/gifs/funny-yes-old-spice-Ld0P4AdeSDjoY",
        "https://giphy.com/gifs/WJjLyXCVvro2I",
        "https://giphy.com/gifs/nfl-chicago-bears-draft-oGO1MPNUVbbk4",
        "https://giphy.com/gifs/the-office-yes-nod-vgUFOWBwBkziE",
        "https://giphy.com/gifs/desusandmero-yes-true-3o7aDb8Qr1TEGbYrew",
        ]
gifs_no = [
        "https://giphy.com/gifs/no-cat-nR4L10XlJcSeQ",
        "https://giphy.com/gifs/reaction-imgfave-RddAJiGxTPQFa",
        "https://giphy.com/gifs/no-TfS8MAR9ucLHW",
        "https://giphy.com/gifs/26tOXgoz0WNQhwb04",
        "https://giphy.com/gifs/W5YVAfSttCqre",
        ]
gifs_hack = [
        "https://giphy.com/gifs/LcfBYS8BKhCvK",
        "https://giphy.com/gifs/world-hack-double-QdFeImLAY3jEs",
        "https://giphy.com/gifs/Siemens--code-matrix-cyber-security-WRoLGgwE4xTQYTxyJg",
        "https://giphy.com/gifs/screen-monitor-closeup-26tn33aiTi1jkl6H6",
        "https://giphy.com/gifs/origins-hacking-heartbleed-rMS1sUPhv95f2",
        ]

cursed_shrek = [
        "https://giphy.com/gifs/get-shrekd-shrecked-3o72F8VCXCSusbmbwk",
        "https://i.redd.it/t29pa09kghf11.jpg",
        "https://i.redd.it/r7e0by9072t01.jpg",
        "https://i.pinimg.com/736x/0d/db/1e/0ddb1ed20fd38f4f354252f6ac4d3d5b.jpg",
        "https://i.redd.it/zsfxatrbwim11.jpg",
        "https://66.media.tumblr.com/c45778c47789dd483e72796b845282fb/4a5c9e72e0393542-20/s640x960/b5463f0c6b656b26273efde31c2763ad42bd2e5f.jpg",
        "https://66.media.tumblr.com/ca835b076dc28568ec1e52b5ac0f62c9/tumblr_pdbzvasvE71xa8qh6o1_500.jpg",
        "https://i.pinimg.com/originals/8a/14/9e/8a149ed4174d01c9c63cedc23a769b87.png",
        "https://78.media.tumblr.com/11d60d69ba8e7fb8d366bd7ce3be7f5c/tumblr_p7l6z1oloa1rvzucio1_500.jpg",
        "https://i.redd.it/jc0sce3hnm411.jpg",
        "https://i.pinimg.com/originals/24/55/94/245594470ed0704eba0c89654c0d0f57.jpg",
        "https://i.ytimg.com/vi/UPSPj3kx3Cc/maxresdefault.jpg",
        "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/26aa084b-6084-4be3-8628-95f078550408/d8ww69j-73437803-5d38-4157-bd3e-b30c18272ee7.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI2YWEwODRiLTYwODQtNGJlMy04NjI4LTk1ZjA3ODU1MDQwOFwvZDh3dzY5ai03MzQzNzgwMy01ZDM4LTQxNTctYmQzZS1iMzBjMTgyNzJlZTcuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.OVKtiWT62iJAFVsqpkGwkgcjyiDa20KtmQFQO_JYVxU",
        "https://tiermaker.com/images/templates/486941557557977.jpg",
        "https://giphy.com/gifs/qIFJYOOi09bk4",
        "https://cdn.discordapp.com/attachments/303536282036862996/742133724212363335/Shrek.mp4",
        ]

memes_list = [
        "https://cdn.discordapp.com/attachments/303536282036862996/742133724212363335/Shrek.mp4",
        "https://youtu.be/jeg_TJvkSjg",
        "https://cdn.discordapp.com/attachments/709925557781135361/740102869407105034/BANISHMENT.mp4",
        "https://cdn.discordapp.com/attachments/726789026354430473/741701605665013820/You_found.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/741691240034074684/CPU.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/740722117145788426/image0.jpg",
        "https://cdn.discordapp.com/attachments/726789026354430473/740359686246629458/bf79vGS.png",
        "https://cdn.discordapp.com/attachments/738196403649773660/738875658209329222/unknown.png",
        "https://cdn.discordapp.com/attachments/738196403649773660/738871058341560330/unknown.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/738501236763918356/aaaaaaaaaaaaaaaa.mp4",
        "https://cdn.discordapp.com/attachments/595188808434188298/738229078720643172/image0-9.png",
        "https://cdn.discordapp.com/attachments/726789026354430473/738211272822095872/81d01e5.jpg",
        "https://cdn.discordapp.com/attachments/644902186874175498/738023862947807263/33cf607.jpg",
        "https://cdn.discordapp.com/attachments/644902186874175498/738162028773900443/1SATnQvqM8kzbim4f.mp4",
        "https://cdn.discordapp.com/attachments/644902186874175498/738191452693200936/uP6rHpiklOK78Wmr.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/738119573731016724/its_been_so_long.mp4",
        "https://cdn.discordapp.com/attachments/738196403649773660/738235309950763069/video0.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/742115644304261210/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/742110255562883132/image0.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/742081156987748463/image0.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/741938999672700950/video0_14.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/741884060158394419/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/741543540924088340/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/741507293157523466/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/741419628068077598/image0.png",
        "https://tenor.com/view/me-when-the-when-the-stevie-stevie-t-gif-17715541",
        "https://cdn.discordapp.com/attachments/570102359913398275/741345251381215262/image3.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/741345251008184491/image2.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/741345250563457054/image1.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/741345247514329118/image0.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/741338972550070322/image1.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/741181872154869760/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/740993055070486568/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/740992934777847873/video0.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/740783661216956516/stick_bug_song.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/740633174471868416/cannibalism.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/740581390042792016/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/740581203727351818/video0.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/740581182466687007/image0.png",
        "https://cdn.discordapp.com/attachments/467039941428248577/740560263807369256/myzaf33jn5f51.png",
        "https://cdn.discordapp.com/attachments/467039941428248577/739248917387935795/824sdnqdzee51.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/740417081681641522/horse.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/740392828441591908/devotion_to_duty.png",
        "https://cdn.discordapp.com/attachments/722870109118660681/740265541843026041/image0.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/740063257976635442/date.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/740061454421721159/im_blue.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/739977651095076996/unknown.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/739600157372448778/image0.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/739232243742146671/cat.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/739161740666732655/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/739161562241040404/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/739161283559030945/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/738908712462188694/h.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/738855218241863730/toilet.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/738849226762747974/inbread_cat.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/738848687366865017/unknown.png",
        "https://cdn.discordapp.com/attachments/570102359913398275/738846284814876692/playing_minecraft.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/738841144389009408/gaming..mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/738837467582562334/image0.jpg",
        "https://cdn.discordapp.com/attachments/570102359913398275/738500447513346048/fuck_brazil.mp4",
        "https://cdn.discordapp.com/attachments/507526277918621697/737976974424801300/noice.mp4",
        "https://5f1e2d7ac3556.htmlsave.net/",
        "https://cdn.discordapp.com/attachments/570102359913398275/738214876815556698/video0.mp4",
        "https://cdn.discordapp.com/attachments/570102359913398275/738164756900479046/rick_astley.mp4",
        ]
